config/routes.rb
Rails.application.routes.draw do
  # Clearance Routes
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/login" => "clearance/sessions#new", as: "sign_in"
  delete "/logout" => "clearance/sessions#destroy", as: "sign_out"
  get "/login" => "clearance/users#new", as: "sign_up"
  # End Clearance
  # 
	get 'friends' => 'friends#index', as: :friends
  get 'friends/:id' => 'friends#show', as: :friends_show
	resources :expenses
	resources :users
	root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
	belongs_to :user
	has_and_belongs_to_many :users
	after_create :send_mail_to_beneficiares_after_create

	monetize :amount_cents, :as => "amount_money"


	def amount
		self.amount_money.to_f
	end

	def payer
		self.user
	end

	def beneficiares
		self.users
	end

	def get_balance_of_user(user)
      @balance = 0      
      nUser = self.users.count
      part = self.amount_money / nUser
      if user.id == self.user.id 
        @balance = self.amount_money - part
      else 
        @balance = 0 - part 
      end
    end

     # Send a mials to inform beneficiares of expenses
    def send_mail_to_beneficiares_after_create 
      self.beneficiares.each do |user|
        UserMailer.send_mail_to_beneficiares(self,user).deliver_later
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_and_belongs_to_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Clearance::Controller
 	protect_from_forgery with: :exception
 	before_action :require_login
  
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @users = User.all
  end

  # GET /expenses/1/edit
  def edit
    @users = User.all
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @users = User.all

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Une dépense a été créée.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Une dépense a été modifiée.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Une dépense a été détruite.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :amount_money, :user_id, user_ids: [])
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

	def index
	    @users = User.all
	end

	def show
	    @friend = User.find(params[:id])
	    
	    @expenses_user = Expense
	                         .joins(:users)
	                         .where('expenses.user_id = (?)', current_user.id)
	                         .where('users.id = (?)', params[:id])

	    @expenses_friend = Expense
	                           .joins(:users)
	                           .where('expenses.user_id = (?)', params[:id])
	                           .where('users.id = (?)', current_user.id)

	    @expenses = @expenses_user + @expenses_friend

	    @user_spent = Money.new(0)
	    @user_debtor = Money.new(0)

	    @expenses.each do |expense|

			@number_of_users = expense.users.count
			@user_expense = expense.amount_money / @number_of_users

			if expense.user_id == current_user.id
			@user_spent += @user_expense
			else
			@user_debtor += @user_expense
			end

	    end

		@global_user = @user_spent - @user_debtor
	
	end

	def friends_params
		permitted = params.require(:user).permit(:current_user_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index	
		@user = User.find(current_user.id)
		@expenses = @user.expenses

		@user_spent = Money.new(0)
		@users_debtor = Money.new(0)

		@expenses.each do |expense|
			@number_of_users = expense.users.count
			@user_expense = expense.amount_money / @number_of_users

			if expense.user_id == @user.id
				@user_spent += @user_expense * (@number_of_users - 1)
			else
				@users_debtor += @user_expense
			end
		end

		@global_user = @user_spent - @users_debtor
	end

	def login

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Un utilisateur a été créé.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Un utilisateur a été modifié.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Un utilisateur a été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "titre" %>
    <%= form.text_field :title, id: :expense_title %>
  </div>

  <div class="field">
    <%= form.label "Montant" %>
    <%= form.text_field :amount_money, id: :expense_amount %>
  </div>

  <div class="field">
    <%= form.label "Payeur" %>
    <%= form.select(
      :user_id,
      options_for_select(@users.map { |e| [e.name, e.id] }))
    %>
  </div>

  <div class="field">
  <%= form.label "Bénéficiaires"  %>
    <%= form.select(
      :user_ids,
      options_for_select(@users.map { |e| [e.name, e.id] }),
      {},
      { :multiple => true})
    %>
  </div>

  <div class="actions">
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1> Modifier dépense </h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice bg-danger"><%= notice %></p>

<h1>Dépenses</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Titre</th>
      <th>Montant</th>
      <th>Payeur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td scope="row"><%= expense.id %></td>
        <td><%= expense.title %></td>
        <td><%= expense.amount_money %></td>
        <td><%= expense.user.name %></td>

        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn btn_secondary">
  <%= link_to "Ajouter une dépense", new_expense_path %>
</button>

app/views/expenses/new.html.erb
<h1>Nouvelle dépense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @expense.title %>
</p>

<p>
  <strong>Montant:</strong>
  <%= @expense.amount_money %>
</p>

<p>
  <strong>Créer par:</strong>
  <%= @expense.user.name %>
</p>

<p>
	<strong>Bénéficiaires:</strong>

	<% @expense.users.each  do |user|  %>
 		<li><%= user.name %></li>
    <% end %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voir les dépenses</h1>
<% @users.each do |user| %>
	<% if current_user.id != user.id %>
			<p><%= link_to user.name, friends_show_path(user) %></td></p>
   	<% end %>
<% end %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Balance</h1>
<div class="container-fluid">
	<% if @global_user < 0 %>
		<p>je dois <%= @global_user.abs %> <%= @global_user.currency %> à <%= @friend.name %></p>
	<% else %>
		<p><%= @friend.name %> me doit <%= @global_user.abs %> <%= @global_user.currency %></p>
	<% end %>
</div>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Les Bons Amis</h1>
<h2>Bonjour, <%= current_user.name %></h2>
<h2>Balance Globale : <%= @global_user %> <%= @global_user.currency %></h2>
<p>Tes amis te doivent <%= @user_spent %> <%= @user_spent.currency %></p>
<p>Tu dois <%= @users_debtor %> <%= @users_debtor.currency %> à tes amis</p>
<button class="btn btn_secondary">
<%= link_to "Ajouter une dépense", new_expense_path%>
</button>

app/views/layouts/_navbar.html.erb
<header class="container">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to "GoodFriend", root_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>  

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Utilisateurs", users_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Dépenses", expenses_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Voir mes dépense", friends_path, :class => 'nav-link' %>
      </li>      
    </ul>
    <ul class="nav navbar-nav navbar-right">
      
        <% if signed_in? %>
        <li class="nav-item ">
          <%= current_user.email %>
        </li>
        <li class="nav-item ">
        <button class="button">
          <%= link_to "Sign out", sign_out_path, method: :delete %>
          </button>
        </li>
        <% else %>        
          <%= link_to "Sign in", sign_in_path %>
        <% end %>        
      </li>
    </ul>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoodFriendSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
  	<%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: false) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nom" %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label "Mail" %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label "Mot de passe" %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Modifier utilisatuer</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Utilisateurs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Nom</th>
      <th>Mail</th>
      <th>Mot de passe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td scope="row"><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button class="btn btn_secondary">
  <%= link_to "Ajouter un utilisateur", new_user_path %>
</button>

app/views/users/login.html.erb
<h1>Connexion</h1>
<br />
<%= form_tag login_path , method: :post do %>

  <div class="form-groups">
    <%= label_tag "Nom" %>
    <%= text_field_tag :name %>
  </div>

  <div class="form-groups">
    <%= label_tag "Mot de passe" %>
    <%= password_field_tag :password%>
  </div>

  <br /><br />
  <input type="submit" class="btn btn-secondary" value="Se connecter" /> ou <a href="/users/new" class="btn btn-primary">S'inscrire</a>

<% end %>

<% console %>

app/views/users/new.html.erb
<h1>Nouvel utilisateur</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Mot de passe:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>